### 生成支付二维码
POST http://localhost:63030/orders/generatepaycode
Content-Type: application/json

{
  "totalPrice" : 1,
  "orderType" : "60201",
  "orderName" : "测试课程01",
  "orderDescrip" : "购买课程:测试课程01",
  "orderDetail" : [{"goodsId":2,"goodsType":"60201","goodsName":"测试课程01","goodsPrice":1}],
  "outBusinessId" : "9"
}

### 查询支付结果
GET localhost:63030/orders/payresult?payNo=1577239361225244672